const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=Number(process.env.PORT||8080),HOST='0.0.0.0',ROOT=__dirname;
const db={users:'users.json',messages:'messages.json',blocks:'blocks.json',notifications:'notifications.json'};const sessions=new Map();
for(const f of Object.values(db))if(!fs.existsSync(path.join(ROOT,f)))fs.writeFileSync(path.join(ROOT,f),'[]');for(const d of ['profiles','media'])if(!fs.existsSync(path.join(ROOT,d)))fs.mkdirSync(path.join(ROOT,d));
const read=f=>{try{return JSON.parse(fs.readFileSync(path.join(ROOT,f),'utf8'))}catch{return[]}};const write=(f,x)=>fs.writeFileSync(path.join(ROOT,f),JSON.stringify(x,null,2));
const uid=()=>crypto.randomBytes(16).toString('hex');const salt=()=>crypto.randomBytes(16).toString('hex');const hash=(p,s)=>crypto.scryptSync(p,s,64).toString('hex');
function cookies(r){return Object.fromEntries((r.headers.cookie||'').split(';').filter(Boolean).map(x=>{let i=x.indexOf('=');return[x.slice(0,i).trim(),decodeURIComponent(x.slice(i+1))]}))}
function me(r){let t=cookies(r).nova_session||r.headers['x-token'];return t?sessions.get(t):null}function out(res,n,x,h={}){res.writeHead(n,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...h});res.end(JSON.stringify(x))}
function body(r,max=12e6){return new Promise((ok,no)=>{let s='';r.on('data',c=>{s+=c;if(s.length>max)no(Error('Payload too large'))});r.on('end',()=>ok(s));r.on('error',no)})}
const pub=u=>({id:u.id,name:u.name,profilePhoto:u.profilePhoto||null,createdAt:u.createdAt});const find=n=>read(db.users).find(u=>u.name.toLowerCase()===String(n||'').trim().toLowerCase());
function blocked(a,b){return read(db.blocks).some(x=>(x.a===a&&x.b===b)||(x.a===b&&x.b===a))}
async function api(req,res,u){
 if(req.method==='POST'&&u.pathname==='/api/register'||req.method==='POST'&&u.pathname==='/api/login'){let d;try{d=JSON.parse(await body(req,1e5))}catch{return out(res,400,{error:'Données invalides'})}let name=String(d.name||'').trim().slice(0,30),p=String(d.password||'');if(!name||p.length<4)return out(res,400,{error:'Nom et mot de passe requis (mot de passe: 4 caractères minimum)' });let users=read(db.users),x=find(name);if(u.pathname==='/api/register'){if(x)return out(res,409,{error:'Ce nom existe déjà'});let s=salt();x={id:uid(),name,salt:s,passwordHash:hash(p,s),createdAt:Date.now(),profilePhoto:null};users.push(x);write(db.users,users)}else{if(!x||hash(p,x.salt)!==x.passwordHash)return out(res,401,{error:'Nom ou mot de passe incorrect'})}let t=uid();sessions.set(t,x);return out(res,200,{ok:true,user:pub(x)},{'Set-Cookie':`nova_session=${t}; HttpOnly; SameSite=Lax; Path=/; Max-Age=2592000`})}
 if(req.method==='POST'&&u.pathname==='/api/logout'){let t=cookies(req).nova_session;sessions.delete(t);return out(res,200,{ok:true},{'Set-Cookie':'nova_session=; Max-Age=0; Path=/; HttpOnly; SameSite=Lax'})}
 let x=me(req);if(u.pathname.startsWith('/api/')&&!x)return out(res,401,{error:'Non connecté'});
 if(req.method==='GET'&&u.pathname==='/api/me')return out(res,200,{user:pub(x)});
 if(req.method==='GET'&&u.pathname==='/api/users'){let q=String(u.searchParams.get('q')||'').toLowerCase(),a=read(db.users).filter(v=>v.id!==x.id&&!blocked(x.id,v.id)&&v.name.toLowerCase().includes(q)).slice(0,50).map(pub);return out(res,200,{users:a})}
 if(req.method==='GET'&&u.pathname==='/api/messages'){let other=find(u.searchParams.get('with'));if(!other)return out(res,404,{error:'Utilisateur introuvable'});if(blocked(x.id,other.id))return out(res,200,{messages:[],blocked:true});let a=read(db.messages).filter(m=>((m.from===x.id&&m.to===other.id)||(m.from===other.id&&m.to===x.id))&&!(m.deletedFor||[]).includes(x.id));return out(res,200,{messages:a.slice(-300),blocked:false})}
 if(req.method==='POST'&&u.pathname==='/api/send'){let d;try{d=JSON.parse(await body(req))}catch{return out(res,400,{error:'Données invalides'})}let to=find(d.to);if(!to)return out(res,404,{error:'Utilisateur introuvable'});if(blocked(x.id,to.id))return out(res,403,{error:'Conversation bloquée'});let m={id:uid(),from:x.id,fromName:x.name,to:to.id,toName:to.name,text:String(d.text||'').slice(0,5000),type:'text',mediaUrl:null,createdAt:Date.now(),deletedFor:[]};if(d.media&&String(d.media.data).startsWith('data:')){let z=String(d.media.data).match(/^data:([^;]+);base64,(.+)$/s);if(z){let ext={'image/jpeg':'jpg','image/png':'png','image/webp':'webp','audio/webm':'webm','audio/ogg':'ogg','audio/mp4':'m4a'}[z[1]]||'bin';let fn=m.id+'.'+ext;fs.writeFileSync(path.join(ROOT,'media',fn),Buffer.from(z[2],'base64'));m.type=z[1].startsWith('audio/')?'audio':'image';m.mediaUrl='/media/'+fn;m.mime=z[1]}}let a=read(db.messages);a.push(m);write(db.messages,a);let n=read(db.notifications);n.push({id:uid(),to:to.id,fromName:x.name,createdAt:Date.now(),read:false});write(db.notifications,n);return out(res,200,{ok:true,message:m})}
 if(req.method==='POST'&&u.pathname==='/api/delete'){let d=JSON.parse(await body(req,1e5)),a=read(db.messages),m=a.find(v=>v.id===d.id);if(!m)return out(res,404,{error:'Message introuvable'});if(d.mode==='everyone'&&m.from===x.id){m.text='Message supprimé';m.type='text';m.mediaUrl=null;m.deletedFor=[m.from,m.to]}else m.deletedFor=[...(m.deletedFor||[]),x.id];write(db.messages,a);return out(res,200,{ok:true})}
 if(req.method==='POST'&&u.pathname==='/api/block'){let d=JSON.parse(await body(req,1e5)),o=find(d.name);if(!o)return out(res,404,{error:'Utilisateur introuvable'});let a=read(db.blocks);a=a.filter(v=>!(v.a===x.id&&v.b===o.id));if(d.block!==false)a.push({a:x.id,b:o.id,createdAt:Date.now()});write(db.blocks,a);return out(res,200,{ok:true,blocked:blocked(x.id,o.id)})}
 if(req.method==='GET'&&u.pathname==='/api/notifications'){return out(res,200,{notifications:read(db.notifications).filter(n=>n.to===x.id).slice(-100).reverse()})}
 if(req.method==='POST'&&u.pathname==='/api/notifications/read'){let a=read(db.notifications);a.forEach(n=>{if(n.to===x.id)n.read=true});write(db.notifications,a);return out(res,200,{ok:true})}
 if(req.method==='POST'&&u.pathname==='/api/profile/photo'){let d=JSON.parse(await body(req,8e6)),z=String(d.data||'').match(/^data:image\/([^;]+);base64,(.+)$/s);if(!z)return out(res,400,{error:'Image invalide'});let ext=z[1].replace(/[^a-z0-9]/gi,'')||'png',fn=x.id+'.'+ext;fs.writeFileSync(path.join(ROOT,'profiles',fn),Buffer.from(z[2],'base64'));let a=read(db.users),v=a.find(q=>q.id===x.id);v.profilePhoto='/profiles/'+fn+'?v='+Date.now();write(db.users,a);x.profilePhoto=v.profilePhoto;return out(res,200,{profilePhoto:v.profilePhoto})}
 return out(res,404,{error:'Route introuvable'})}
function staticFile(res,p){let f=path.normalize(path.join(ROOT,'public',p==='/'?'index.html':p));if(!f.startsWith(path.join(ROOT,'public')))return res.end();fs.readFile(f,(e,b)=>{if(e){res.writeHead(404);return res.end('Not found')}let ext=path.extname(f),types={'.html':'text/html; charset=utf-8','.css':'text/css','.js':'application/javascript','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream'});res.end(b)})}
http.createServer(async(req,res)=>{try{let u=new URL(req.url,'http://localhost');if(u.pathname.startsWith('/api/'))return await api(req,res,u);if(u.pathname.startsWith('/media/')||u.pathname.startsWith('/profiles/')){let f=path.normalize(path.join(ROOT,u.pathname.slice(1)));if(!f.startsWith(ROOT)||!fs.existsSync(f))return res.end();return fs.createReadStream(f).pipe(res)}staticFile(res,u.pathname)}catch(e){console.error(e);out(res,500,{error:'Erreur serveur'})}}).listen(PORT,HOST,()=>console.log('NovaChat V7 sur http://'+HOST+':'+PORT));
